version: "3.0"
services:
    php:
        build:
            context: .
            dockerfile: Dockerfile-PHP
        expose:
            - 9000
        volumes:
            - ".:/var/www/html"
            - compiled-css:/var/www/html/assets/css
            - node-modules:/var/www/html/node_modules
        networks:
            - server

    nginx:
        build: ./nginx/
        ports:
            - 8000:80
        volumes:
            - ".:/var/www/html:ro"
        networks:
            - server
        depends_on:
            - php

volumes:
    compiled-css:
    node-modules:

networks:
    server:
