FROM php:7.0-fpm
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /var/www/html
RUN ls /var/www/html
RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install gnupg curl software-properties-common ruby-ffi ruby-dev -y
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get install nodejs -y
RUN gem install sass
#RUN npm install -g npm@latest
#RUN npm install
#RUN sass assets/scss/default.scss assets/css/compiled.css
