version: "3.0"

services:
            
    nginx:
        build: ./nginx/
        ports:
            - 8000:80
        volumes:
            - "${PROJECT_ROOT}:/var/www/html:ro"
        networks:
            - server
        depends_on:
            - php

    php:
        build: ./php/
        expose:
            - 9000
        volumes:
            - "${PROJECT_ROOT}:/var/www/html"
        networks:
            - server

networks:
    server:
