version: "3.0"
services:
    php:
        build:
            context: .
            dockerfile: Dockerfile-PHP
        expose:
            - 9000
        volumes:
            - .:/var/www/html:rw
        networks:
            - server

    nginx:
        build: ./nginx/
        ports:
            - 8000:80
        volumes:
            - .:/var/www/html:rw
        networks:
            - server
        depends_on:
            - php

networks:
    server:
