version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-node-browsers
    steps:
      - run: mkdir -p /tmp/rototype && cd /tmp/prototype
      - checkout
      - run:
          name: Update apt-get
          command: sudo apt-get update
      - run:
          name: Install pip and ruby-dev
          command: sudo apt-get install python-pip ruby-dev
      - run:
          name: Install SASS
          command: sudo gem install sass
      - run:
          name: Update npm
          command: sudo npm install -g npm@latest
      - run:
          name: Install html5validator
          command: pip install html5validator
      - run:
          name: Install npm dependencies
          command: npm install
      - run:
          name: Validate HTML
          command: ~/.local/bin/html5validator --root . --blacklist node_modules 
      - run:
          name: Compile SCSS
          command: sass assets/scss/* assets/css/compiled.css
      - persist_to_workspace:
          root: tmp
          paths:
            - prototype
    
  deploy:
    machine:
        enabled: true
    steps:
      - attach_workspace:
          at: prototype
      - run:
          name: Get oriented
          command: pwd; ls
      - run:
          name: Deploy to S3
          command: aws s3 sync /tmp/prototype/ s3://prototype.ustaxcourt.gov --delete
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
