version: 2
jobs:
  test-3.6:
    docker:
      - image: circleci/openjdk:8-jdk-node-browsers
    steps:
      - checkout
      - run:
          name: Update npm
          command: sudo npm install -g npm@latest
      - run:
          name: Install npm dependencies
          command: npm install
      - run:
          name: Install html5validator
          command: pip install html5validator
      - run:
          name: Validate html
          command: html5validator --root . --also-check-css
      - run:
          name: Move USWDS assets to webroot
          command: cp -R node_modules/uswds/dist/ assets/uswds/
workflows:
  version: 2
  build_and_test:
    jobs:
      - test-3.6
