version: 2
jobs:
  test-3.6:
    docker:
      - image: python:3.6-stretch
    steps:
      - run:
          name: install Java
          command: apt-get update && apt-get install -y openjdk-8-jre
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: Install npm
          command: npm install
      - run:
          name: install
          command: pip install html5validator
      - run:
          name: validate html
          command: html5validator --root . --also-check-css
      - run:
          name: 
          command: cp -R node_modules/uswds/dist/ assets/uswds/
workflows:
  version: 2
  build_and_test:
    jobs:
      - test-3.6
