version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-node-browsers
    steps:
      - checkout
      - run:
          name: Install pip and ruby-dev
          command: sudo apt-get install python-pip ruby-dev
      - run:
          name: Install sass
          command: sudo gem install sass
      - run:
          name: Update npm
          command: sudo npm install -g npm@latest
      - run:
          name: Install html5validator
          command: pip install html5validator
      - run:
          name: Install npm dependencies
          command: npm install
      - run:
          name: Validate html
          command: ~/.local/bin/html5validator --root . --blacklist node_modules 
      - run:
          name: Compile SCSS
          command: sass assets/scss/* assets/css/compiled.css
  deploy:
    machine:
        enabled: true
    steps:
      - run:
          name: List pwd
          command: pwd
      - run:
          name: List directory contents
          command: ls -la
      - run:
          name: Deploy to S3
          command: aws s3 sync . s3://prototype.ustaxcourt.gov --delete
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy
