version: 2
jobs:
  test-3.6:
    docker:
      - image: circleci/openjdk:8-jdk-node-browsers
    steps:
      - checkout
      - run:
          name: Install pip and ruby-dev
          command: sudo apt-get install python-pip ruby-dev
      - run:
          name: Install sass
          command: sudo gem install sass
      - run:
          name: Update npm
          command: sudo npm install -g npm@latest
      - run:
          name: Install npm dependencies
          command: npm install
      - run:
          name: Install html5validator
          command: pip install html5validator
      - run:
          name: Validate html
          command: ~/.local/bin/html5validator --root . --also-check-css
      - run:
          name: Compile SCSS
          command: sass assets/scss/* assets/css/compiled.css
workflows:
  version: 2
  build_and_test:
    jobs:
      - test-3.6
