version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-node-browsers
    steps:
      - run: mkdir -p /tmp/prototype && cd /tmp/prototype
      - checkout
      - run:
          name: Install apt-get packages
          command: sudo apt-get update && sudo apt-get install python-pip ruby-dev awscli
      - run:
          name: Install SASS
          command: sudo gem install sass
      - run:
          name: Update npm
          command: sudo npm install -g npm@latest
      - run:
          name: Install html5validator
          command: pip install html5validator
      - run:
          name: Install npm dependencies
          command: npm install
      - run:
          name: Validate HTML
          command: ~/.local/bin/html5validator --root . --blacklist node_modules 
      - run:
          name: Compile SCSS
          command: sass assets/scss/* assets/css/compiled.css
      - run:
          name: Check that we're in the right directory
          command: pwd; ls
      - run:
          name: Deploy to S3
          command: aws s3 sync /tmp/prototype/ s3://prototype.ustaxcourt.gov --delete
